### ISSUE TITLE
pdflatex not found outside of RStudio

### ISSUE THREAD

**Issue by wjakethompson** [wjakethompson/jayhawkdown#1]
Example document knits to PDF just fine using the "Knit" button in RStudio, but when trying to knit outside of RStudio (i.e., `bookdown::render_book("index.rmd", "jayhawkdown::thesis_pdf")`), getting an error:

```
/bin/sh: pdflatex: command not found
```

However, pdflatex is definitely present:

```
$ which pdflatex
/Library/TeX/texbin/pdflatex

$ echo $PATH
//anaconda/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Library/TeX/texbin
```

**Comment by wjakethompson** [comment]
Known issue apparently with newer MacOS (El Capitan on from what I can tell).

https://stackoverflow.com/questions/28331343/knitting-to-pdf-in-r
https://stackoverflow.com/questions/22081991/rmarkdown-pandoc-pdflatex-not-found

Need to create a symbolic link to the $PATH

```sh
sudo ln -s /Library/TeX/texbin/pdflatex /usr/local/bin/pdflatex
```

Where the first path is the result from `$ which pdflatex`.

**Comment by yvestch** [comment]
I had a similar issue as I wasn't able to knit pdf file & solved it by installing & running tinitex packages using those commands in the console -- not the terminal

> install.packages("tinytex")
> tinytex::install_tinytex()

**Comment by vinny-martinson** [comment]
> I had a similar issue as I wasn't able to knit pdf file & solved it by installing & running tinitex packages using those commands in the console -- not the terminal
> 
> > install.packages("tinytex")
> > tinytex::install_tinytex()

Worked perfeclty.

**Comment by SergioARico** [comment]
> I had a similar issue as I wasn't able to knit pdf file & solved it by installing & running tinitex packages using those commands in the console -- not the terminal
> 
> > install.packages("tinytex")
> > tinytex::install_tinytex()

Still working!

**Comment by CNNmar** [comment]
> I had a similar issue as I wasn't able to knit pdf file & solved it by installing & running tinitex packages using those commands in the console -- not the terminal
> 
> > install.packages("tinytex")
> > tinytex::install_tinytex()

Still working!

**Comment by AlifUnseen** [comment]
Still working!

> I had a similar issue as I wasn't able to knit pdf file & solved it by installing & running tinitex packages using those commands in the console -- not the terminal
> 
> > install.packages("tinytex")
> > tinytex::install_tinytex()
